### ISSUE TITLE
Tutorials review

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/training#50]
Review all tutorials to ensure they work as intended with Invenio v3.2

**Comment by kpsherva** [comment]
postponed for after v3.2.0a6 released

**Comment by roksys** [comment]
- [x] https://github.com/inveniosoftware/training/tree/master/00-prerequisites
- [x] https://github.com/inveniosoftware/training/tree/master/01-getting-started
- [x] https://github.com/inveniosoftware/training/tree/master/02-invenio-tour
- [x] https://github.com/inveniosoftware/training/tree/master/03-infrastructure-tour
- [x] https://github.com/inveniosoftware/training/tree/master/04-running-invenio
- [x] https://github.com/inveniosoftware/training/tree/master/05-customizing-invenio
- [x] https://github.com/inveniosoftware/training/tree/master/06-developing-with-invenio
- [x] https://github.com/inveniosoftware/training/tree/master/07-data-models-new-field
- [x] https://github.com/inveniosoftware/training/tree/master/08-data-models-from-scratch
- [x] https://github.com/inveniosoftware/training/tree/master/09-deposit-form
- [x] https://github.com/inveniosoftware/training/tree/master/10-indexing-records
- [x] https://github.com/inveniosoftware/training/tree/master/11-linking-records
- [x] https://github.com/inveniosoftware/training/tree/master/12-managing-access
- [x] https://github.com/inveniosoftware/training/tree/master/13-securing-your-instance
- [x] https://github.com/inveniosoftware/training/tree/master/14-deployment-monitoring
- [ ] https://github.com/inveniosoftware/training/tree/master/15-application-architecture

**Comment by KonstantinaStoikou** [comment]
After doing the training with 3.2v these are the issues we encountered:
- [x] cookiecutter version should be 3.2 (including the start-from.sh script)
- [x] test_api_simple_flow has been removed https://github.com/inveniosoftware/training/tree/master/06-developing-with-invenio#step-4-running-tests
- [x] authors only has v6 for elasticsearch
- [x] in training 10 step 2 the signal receiver already exists and is missing the "arguments" parameter
- [x] training 8 has a TODO to be completed (TODO add autonomous exercise)
- [x] training 10 step 2, indexer.py already exists and ext.py has a different content
- [x] training 15 is empty 
- [x] start-from.sh copies my-site inside my-site and not just the content of my-site
- [ ] it would be nice to explain when things are stored in db and when in elasticsearch (in the context of signals)
- [ ] training 11 step 5, invenio records create doesn't exist anymore. This makes the author creation need to be part of the marshmallow schema. 
- [ ] training 11, the records module config.py doesn't have an entrypoint in the setup.py and therefore the records-files config is not loaded. /files is not registered
- [ ] config.py has not consistency in dictionaries, it uses dict() in the solution but {} in the training
- [x] _new_record_payload in tests/api/test_api_record_files.py is syntactically incorrect but is doesn't fail because it is not used (https://github.com/inveniosoftware/cookiecutter-invenio-instance/pull/213)

**Comment by topless** [comment]
Detailed status https://codimd.web.cern.ch/_4rwJxTSTz2tDcWWVn4NHA?edit
